// Export bundle (will be generated by postinstall)
const bundle = require('./generated/bundle/wdk-worklet.mobile.bundle.js');
// Export HRPC
const HRPC = require('./src/hrpc/index.js');

module.exports = {
  bundle,
  HRPC
};