// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */

const { c, RPC, RPCStream, RPCRequestStream } = require('hrpc/runtime')
const { getEncoding } = require('./messages.js')

const methods = new Map([
  ['@wdk-core/log', 0],
  [0, '@wdk-core/log'],
  ['@wdk-core/workletStart', 1],
  [1, '@wdk-core/workletStart'],
  ['@wdk-core/dispose', 2],
  [2, '@wdk-core/dispose'],
  ['@wdk-core/callMethod', 3],
  [3, '@wdk-core/callMethod']
])

class HRPC {
  constructor (stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@wdk-core/log', getEncoding('@wdk-core/log-request')],
      ['@wdk-core/workletStart', getEncoding('@wdk-core/workletStart-request')],
      ['@wdk-core/dispose', getEncoding('@wdk-core/dispose-request')],
      ['@wdk-core/callMethod', getEncoding('@wdk-core/callMethod-request')]
    ])
    this._responseEncodings = new Map([
      ['@wdk-core/workletStart', getEncoding('@wdk-core/workletStart-response')],
      ['@wdk-core/callMethod', getEncoding('@wdk-core/callMethod-response')]
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(null, null, req.createResponseStream(), responseEncoding)
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(req, responseEncoding, req.createRequestStream(), requestEncoding)
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(req, responseEncoding, req.createRequestStream(), requestEncoding, req.createResponseStream(), responseEncoding)
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call (name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync (name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
    }
    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(request, responseEncoding, null, null, request.createRequestStream(), requestEncoding)
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(request, responseEncoding, request.createResponseStream(), responseEncoding, request.createRequestStream(), requestEncoding)
    }
  }

  log (args) {
    return this._callSync('@wdk-core/log', args)
  }

  async workletStart (args) {
    return this._call('@wdk-core/workletStart', args)
  }

  dispose (args) {
    return this._callSync('@wdk-core/dispose', args)
  }

  async callMethod (args) {
    return this._call('@wdk-core/callMethod', args)
  }

  onLog (responseFn) {
    this._handlers['@wdk-core/log'] = responseFn
  }

  onWorkletStart (responseFn) {
    this._handlers['@wdk-core/workletStart'] = responseFn
  }

  onDispose (responseFn) {
    this._handlers['@wdk-core/dispose'] = responseFn
  }

  onCallMethod (responseFn) {
    this._handlers['@wdk-core/callMethod'] = responseFn
  }

  _requestIsStream (command) {
    return [
    ].includes(command)
  }

  _responseIsStream (command) {
    return [
    ].includes(command)
  }

  _requestIsSend (command) {
    return [
      '@wdk-core/log',
      '@wdk-core/dispose'
    ].includes(command)
  }
}

module.exports = HRPC
