// eslint-disable-next-line no-undef
// Handle unhandled promise rejections and exceptions
if (typeof process !== 'undefined' && process.on) {
  process.on('unhandledRejection', (error) => {
    console.error('Unhandled promise rejection in worklet:', error)
  })
  process.on('uncaughtException', (error) => {
    console.error('Uncaught exception in worklet:', error)
  })
}

// Initialize core dependencies
// eslint-disable-next-line no-undef
const { IPC: BareIPC } = BareKit
const HRPC = require('./hrpc')
const rpcException = require('../src/exceptions/rpc-exception')

// Load wallet modules from generated file (ensures proper bundling)
// This file is generated by scripts/generate-wallet-modules.js from schema.json
let WDK = null
let walletManagers = {}
let requiredNetworks = []
let wdkLoadError = null

try {
  const walletModules = require('../generated/wallet-modules.js')
  WDK = walletModules.WDK
  walletManagers = walletModules.walletManagers
  requiredNetworks = walletModules.requiredNetworks
  
  console.log('Loaded wallet modules:', Object.keys(walletManagers).join(', '))
} catch (error) {
  wdkLoadError = {
    message: error?.message || String(error),
    stack: error?.stack,
    name: error?.name,
    code: error?.code
  }
  WDK = null
  walletManagers = {}
  requiredNetworks = []
}

// Initialize RPC
const IPC = BareIPC
const rpc = new HRPC(IPC)

// State
let wdk = null

// Helper functions
const withErrorHandling = (handler) => {
  return async (...args) => {
    try {
      return await handler(...args)
    } catch (error) {
      throw new Error(rpcException.stringifyError(error))
    }
  }
}

/**
 * Generalized function to call any WDK account method
 * This provides a dev-friendly way to call account methods without needing individual handlers
 * 
 * @param {string} methodName - The method name to call on the account (e.g., 'getAddress', 'getBalance')
 * @param {string} network - Network name (e.g., 'ethereum', 'spark')
 * @param {number} accountIndex - Account index
 * @param {any} args - Arguments to pass to the method
 * @param {object} options - Optional configuration
 * @param {function} options.transformResult - Optional function to transform the result
 * @param {any} options.defaultValue - Default value to return if method doesn't exist
 * @returns {Promise<any>} The result from the account method
 */
const callWdkMethod = async (methodName, network, accountIndex, args = null, options = {}) => {
  if (!wdk) {
    throw new Error('WDK not initialized. Call workletStart first.')
  }
  
  const account = await wdk.getAccount(network, accountIndex)
  
  if (typeof account[methodName] !== 'function') {
    if (options.defaultValue !== undefined) {
      console.warn(`${methodName} not available for network: ${network}, returning default value`)
      return options.defaultValue
    }
    const availableMethods = Object.keys(account)
      .filter(key => typeof account[key] === 'function')
      .join(', ')
    throw new Error(
      `Method "${methodName}" not found on account for network "${network}". ` +
      `Available methods: ${availableMethods}`
    )
  }
  
  const result = await account[methodName](args)
  
  if (options.transformResult) {
    return options.transformResult(result)
  }
  
  return result
}

// RPC Handlers
rpc.onWorkletStart(withErrorHandling(async (init) => {
  if (!WDK) {
    const errorMsg = wdkLoadError
      ? `WDK failed to load: ${wdkLoadError.message}\nStack: ${wdkLoadError.stack || 'No stack trace'}`
      : 'WDK not loaded - unknown error during initialization'
    throw new Error(errorMsg)
  }
  
  if (wdk) {
    console.log('Disposing existing WDK instance...')
    wdk.dispose()
  }
  
  const networkConfigs = JSON.parse(init.config || '{}')
  const missingNetworks = requiredNetworks.filter(network => !networkConfigs[network])
  
  if (missingNetworks.length > 0) {
    throw new Error(`Missing network configurations: ${missingNetworks.join(', ')}`)
  }
  
  console.log('Initializing WDK with seed phrase')
  wdk = new WDK(init.seedPhrase)
  
  for (const [networkName, config] of Object.entries(networkConfigs)) {
    if (config && typeof config === 'object') {
      const walletManager = walletManagers[networkName]
      
      if (!walletManager) {
        throw new Error(`No wallet manager found for network: ${networkName}`)
      }
      
      console.log(`Registering ${networkName} wallet`)
      wdk.registerWallet(networkName, walletManager, config)
    }
  }
  
  console.log('WDK initialization complete')
  return { status: 'started' }
}))

/**
 * Generic handler for all WDK account methods
 * This single handler can call any method on any WDK account dynamically
 * No special handling - just calls the method and returns the raw result
 */
rpc.onCallMethod(withErrorHandling(async (payload) => {
  const { methodName, network, accountIndex, args: argsJson } = payload
  
  // Parse args if provided (JSON string)
  const args = argsJson ? JSON.parse(argsJson) : null
  
  // Call the method directly - no special handling
  const result = await callWdkMethod(
    methodName,
    network,
    accountIndex,
    args
  )
  
  // Return as JSON string (raw result, no transformation)
  return { result: JSON.stringify(result) }
}))

rpc.onDispose(withErrorHandling(() => {
  if (wdk) {
    wdk.dispose()
    wdk = null
  }
}))
